FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements-ml-api.txt ./
RUN pip install --no-cache-dir -r requirements-ml-api.txt
COPY ml_api ./ml_api
EXPOSE 8000
